- name: Create vite/react project
  command: npm create vite@latest "{{ appname }}" -- --template react-ts --types
  args:
    chdir: "{{ dest }}"

- name: install
  command: yarn
  args:
    chdir: "{{ dest }}/{{ appname }}"

- name: Add yarn packages to dependencies
  command: yarn add {{ item }}
  with_items:
    - "react"
    - "react-dom"
    - "react-router-dom"
    - "react-query"
    - "react-hook-form"
    - "@react-google-maps/api"
    - "leaflet"
    - "formik"
    - "yup"
    - "@nanostores/react"
    - "react-leaflet"
    - "@stripe/stripe-js"
    - "@stripe/react-stripe-js"
  args:
    chdir: "{{ dest }}/{{ appname }}"

- name: Add yarn packages to devDependencies
  command: yarn add -D {{ item }}
  with_items:
    - "@testing-library/dom"
    - "@testing-library/jest-dom"
    - "@testing-library/react"
    - "@testing-library/user-event"
    - "@types/jest"
    - "jsdom"
    - "vitest"
    - "sass"
  args:
    chdir: "{{ dest }}/{{ appname }}"

- name: add vite.config.ts
  copy:
    src: vite/vite.config.ts
    dest: "{{ dest }}/{{ appname }}"

- name: Create tests directory
  file:
    path: "{{ dest }}/{{ appname }}/tests"
    state: directory
    mode: "0755"

- name: add tests/setup.ts
  copy:
    src: "{{ item }}"
    dest: "{{ dest }}/{{ appname }}/tests"
  with_items:
    - vite/tests/setup.ts
    - vite/tests/App.test.tsx

- name: Add test to package.json
  command: npx json -I -f package.json -e 'this.scripts.test="vitest"'
  args:
    chdir: "{{ dest }}/{{ appname }}"

- name: Add normalize css to index.html
  lineinfile:
    path:  "{{ dest }}/{{ appname }}/index.html"
    line: '    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">'
    insertbefore: '</head>'
    state: present

- name: Copy makefile
  copy:
    src: vite/Makefile
    dest: "{{ dest }}/{{ appname }}/Makefile"

- name: Create utils directory
  file:
    path: "{{ dest }}/{{ appname }}/src/{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - services
    - components
    - constants
    - utils

- name: Copy utils file
  copy:
    src: js/utils.ts
    dest: "{{ dest }}/{{ appname }}/src/utils/index.ts"

- name: Copy services file
  copy:
    src: js/services.ts
    dest: "{{ dest }}/{{ appname }}/src/services/index.ts"

- name: Copy constants file
  copy:
    src: js/constants.ts
    dest: "{{ dest }}/{{ appname }}/src/constants/index.ts"
