- name: Scaffold Application
  hosts: localhost
  vars_prompt:
    - name: appname
      prompt: What should we call your new project?
      private: false
  roles:
    - { role: before, tags: [always] }
    - { role: html, tags: [html] }
    - { role: rails, tags: [rails, railsreact, graphql] }
    - { role: vite, tags: [vite, formik] }
    - { role: node, tags: [node] }
    - { role: astro, tags: [astro] }
    - { role: formik, tags: [formik, railsreact, graphql] }
    - { role: graphql, tags: [graphql] }
    - { role: git, tags: [always] }
