- name: Scaffold Application
  hosts: localhost
  vars_prompt:
    - name: appname
      prompt: What should we call your new project?
      private: false
  roles:
    - { role: html, tags: [html] }
    - { role: rails, tags: [rails] }
    - { role: git, tags: [always] }
