services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5496:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '6375:6375'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      NODE_ENV: development # Set development environment

volumes:
  postgres-data:
