tldr:
	@echo Available commands
	@echo ------------------
	@grep '^[[:alpha:]][^:[:space:]]*:' Makefile | cut -d ':' -f 1 | sort -u | sed 's/^/make /'
%:
	@$(MAKE) tldr
dev:
	./bin/dev -p 5260
dokku:
	@echo Run the following commands:
	@echo "➜ ssh dokku"
	@echo "dokku ➜ newapp {{ appname }}"
