tldr:
	@echo Available commands
	@echo ------------------
	@grep '^[[:alpha:]][^:[:space:]]*:' Makefile | cut -d ':' -f 1 | sort -u | sed 's/^/make /'
%:
	@$(MAKE) tldr
dev:
	docker-compose up --build
dokku:
	@echo "ssh dokku && doknode {{ appname }}"
