- name: Create target directory
  file:
    path: "{{ dest }}/{{ appname }}/"
    state: directory
    mode: "0755"

- name: Copy package.json
  template:
    src: node/package.json.j2
    dest: "{{ dest }}/{{ appname }}/package.json"

- name: Copy makefile
  template:
    src: node/Makefile.j2
    dest: "{{ dest }}/{{ appname }}/Makefile"

- name: Copy top level files
  copy:
    src: "{{ item }}"
    dest: "{{ dest }}/{{ appname }}"
  with_items:
    - node/server.js
    - node/Dockerfile
    - node/docker-compose.yml
    - node/.dockerignore

- name: Setup node
  command: yarn add express sequelize pg pg-hstore dotenv
  args:
    chdir: "{{ dest }}/{{ appname }}"

- name: Create github directory
  file:
    path: "{{ dest }}/{{ appname }}/.github/workflows"
    state: directory
    mode: "0755"

- name: Copy github dokku actions file to target directory
  template:
    src: github-actions/dokku.yml.j2
    dest: "{{ dest }}/{{ appname }}/.github/workflows/dokku.yml"
