- name: Create components directory
  file:
    path: "{{ dest }}/{{ appname }}/src/components"
    state: directory
    mode: "0755"

- name: Copy Form
  copy:
    src: "{{ item }}"
    dest: "{{ dest }}/{{ appname }}/src/components"
  with_items:
    - "formik/components/FormPage.tsx"
    - "formik/components/FormPage.scss"
    - "formik/components/SwitchTheme.tsx"
    - "formik/components/SwitchTheme.scss"
    - "formik/components/HocsPage.tsx"
    - "formik/components/CartPage.tsx"

- name: Copy main and App
  copy:
    src: "{{ item }}"
    dest: "{{ dest }}/{{ appname }}/src"
  with_items:
    - "formik/main.tsx"
    - "formik/App.tsx"

- name: Create contexts directory
  file:
    path: "{{ dest }}/{{ appname }}/src/contexts"
    state: directory
    mode: "0755"

- name: Copy main context
  copy:
    src: "formik/contexts/index.tsx"
    dest: "{{ dest }}/{{ appname }}/src/contexts/index.tsx"


- name: copy hooks examples
  copy:
    src: "{{ item }}"
    dest: "{{ dest }}/{{ appname }}/src/hooks"
  with_items:
    - formik/hooks/hocs.tsx
    - formik/hooks/renderprops.tsx

- name: Copy routes file
  copy:
    src: formik/routes/index.tsx
    dest: "{{ dest }}/{{ appname }}/src/routes/index.tsx"

- name: copy redux store
  copy:
    src: formik/redux/store.ts
    dest: "{{ dest }}/{{ appname }}/src/redux/store.ts"

- name: copy redux slices
  copy:
    src: "{{ item }}"
    dest: "{{ dest }}/{{ appname }}/src/redux/slices"
  with_items:
    - formik/redux/slices/cart.ts
