- name: Create components directory
  file:
    path: "{{ dest }}/{{ appname }}/src/components"
    state: directory
    mode: "0755"

- name: Copy Form
  copy:
    src: "{{ item }}"
    dest: "{{ dest }}/{{ appname }}/src/components"
  with_items:
    - "formik/FormPage.tsx"
    - "formik/FormPage.scss"
    - "formik/SwitchTheme.tsx"
    - "formik/SwitchTheme.scss"
    - "formik/HocsPage.tsx"

- name: Copy main App
  copy:
    src: "formik/App.tsx"
    dest: "{{ dest }}/{{ appname }}/src/App.tsx"

- name: Create contexts directory
  file:
    path: "{{ dest }}/{{ appname }}/src/contexts"
    state: directory
    mode: "0755"

- name: Copy main context
  copy:
    src: "formik/contexts/index.tsx"
    dest: "{{ dest }}/{{ appname }}/src/contexts/index.tsx"


- name: copy hooks examples
  copy:
    src: "{{ item }}"
    dest: "{{ dest }}/{{ appname }}/src/hooks"
  with_items:
    - formik/hooks/hocs.tsx
    - formik/hooks/renderprops.tsx


- name: Copy routes file
  copy:
    src: formik/routes/index.tsx
    dest: "{{ dest }}/{{ appname }}/src/routes/index.tsx"
