- name: Create target directory
  file:
    path: "{{ dest }}/{{ appname }}/"
    state: directory
    mode: "0755"

- name: Copy html files to target directory
  copy:
    src: "{{ item }}"
    dest: "{{ dest }}/{{ appname }}"
  with_items:
    - html/index.html
    - html/styles.css
    - html/script.js
