name: Test
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python3 -m venv ~/.pyvenv-ansible
          source ~/.pyvenv-ansible/bin/activate
          pip install ansible

      - name: Install ansible requirements
        run: |
          source ~/.pyvenv-ansible/bin/activate
          ansible-galaxy collection install -r requirements.yml

      - name: makes html
        run: |
          source ~/.pyvenv-ansible/bin/activate
          ansible-playbook main.yml -i hosts --tags "html" -e "curdir=$(pwd) appname=test_project"
