name: Test
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python3 -m venv ~/.pyvenv-ansible
          source ~/.pyvenv-ansible/bin/activate
          pip install ansible

      - name: Install ansible requirements
        run: |
          source ~/.pyvenv-ansible/bin/activate
          ansible-galaxy collection install -r requirements.yml

      - name: make a gitconfig
        run: |
          echo -e "[user]
            name = github-runner
            email = githubrunner@google.ba
          " > ~/.gitconfig

      - name: is gitconfig there
        run: cat ~/.gitconfig

      - name: makes html
        run: |
          source ~/.pyvenv-ansible/bin/activate
          ansible-playbook main.yml -i hosts --tags "html" -e "curdir=$(pwd) appname=html_test_project"

      - name: makes vite
        run: |
          source ~/.pyvenv-ansible/bin/activate
          ansible-playbook main.yml -i hosts --tags "vite" -e "curdir=$(pwd) appname=vite_test_project"

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: makes node
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        run: |
          source ~/.pyvenv-ansible/bin/activate
          ansible-playbook main.yml -i hosts --tags "node" -e "curdir=$(pwd) appname=node_test_project"

      # - name: Install Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '3.0'

      # - name: Install Rails
      #   run: gem install rails

      # - name: makes rails
      #   env:
      #     DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
      #   run: |
      #     source ~/.pyvenv-ansible/bin/activate
      #     ansible-playbook main.yml -i hosts --tags "rails" -e "curdir=$(pwd) appname=rails_test_project"
