
- name: Create astro project
  command: 	yarn create astro "{{ appname }}" --typescript strict --template minimal --git --install --skip-houston
  args:
    chdir: "{{ dest }}"

- name: add react
  command: 	yarn astro add react -y
  args:
    chdir: "{{ dest }}/{{ appname }}"

- name: Add normalize css to index.html
  lineinfile:
    path:  "{{ dest }}/{{ appname }}/src/pages/index.astro"
    line: '    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">'
    insertbefore: '</head>'
    state: present

- name: add astro.config.ts
  copy:
    src: astro/astro.config.mjs
    dest: "{{ dest }}/{{ appname }}"

- name: Create top level directories
  file:
    path: "{{ dest }}/{{ appname }}/src/{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - services
    - components
    - constants
    - utils

- name: Copy utils file
  copy:
    src: js/utils.ts
    dest: "{{ dest }}/{{ appname }}/src/utils/index.ts"

- name: Copy services file
  copy:
    src: js/services.ts
    dest: "{{ dest }}/{{ appname }}/src/services/index.ts"

- name: Copy constants file
  copy:
    src: js/constants.ts
    dest: "{{ dest }}/{{ appname }}/src/constants/index.ts"
